[package]
name = "eo-core"
description = "Array model, data types and georeferencing for eoview"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
proj4rs = { version = "0.2", default-features = false, features = ["crs-definitions"] }
